INSERT INTO tb_game_list (name) VALUES ('Aventura e RPG');
INSERT INTO tb_game_list (name) VALUES ('Jogos de plataforma');

INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Mass Effect Trilogy', 4.8, 2012, 'Role-playing (RPG), Shooter', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/1.png', 'Uma épica jornada espacial com escolhas impactantes e ação intensa.', 'A trilogia Mass Effect conta a história do Comandante Shepard enquanto ele luta para salvar a galáxia de uma ameaça antiga. Com um foco em narrativa, personagens profundos e escolhas morais, os jogadores se envolvem em uma experiência de RPG imersiva com combate dinâmico e uma trama envolvente.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Red Dead Redemption 2', 4.7, 2018, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/2.png', 'Uma história emocionante de um fora da lei na virada do século XX.', 'Red Dead Redemption 2 é um jogo de mundo aberto que segue Arthur Morgan, um fora da lei da gangue Van der Linde, enquanto ele lida com a queda do Velho Oeste. Com gráficos deslumbrantes, uma narrativa imersiva e mecânicas realistas, o jogo oferece uma experiência inesquecível de exploração e aventura no ambiente brutal e imersivo do Oeste americano.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('The Witcher 3: Wild Hunt', 4.7, 2014, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/3.png', 'Uma busca épica por uma filha adotiva em um mundo cheio de monstros e magia.', 'The Witcher 3: Wild Hunt segue Geralt de Rivia, um caçador de monstros, enquanto ele busca sua filha adotiva, Ciri, em um mundo vasto e aberto, cheio de criaturas, magia e personagens intrigantes. Com uma história profunda e ramificada, escolhas morais complexas e um mundo vivo e dinâmico, é um dos maiores RPGs da história dos videogames.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sekiro: Shadows Die Twice', 3.8, 2019, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/4.png', 'Desafios implacáveis em um Japão feudal inspirado no samurai.', 'Sekiro: Shadows Die Twice coloca os jogadores no papel de um samurai, Sekiro, em busca de vingança e resgate em um Japão feudal repleto de perigos sobrenaturais e inimigos poderosos. Com mecânicas desafiadoras de combate e uma história emocionante, o jogo exige precisão e estratégia para superar obstáculos imensos.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ghost of Tsushima', 4.6, 2012, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/5.png', 'Vivencie a luta de um samurai para proteger sua terra invadida.', 'Ghost of Tsushima segue Jin Sakai, um samurai no Japão feudal, que deve escolher entre honrar seu código samurai ou adotar táticas mais furtivas para proteger sua terra de invasores mongóis. Com belos cenários, combate fluido e uma narrativa emocionante, o jogo oferece uma profunda exploração do Japão medieval e da honra dos samurais.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Super Mario World', 4.7, 1990, 'Platform', 'Super Ness, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/6.png', 'Uma das maiores aventuras de plataforma de todos os tempos.', 'Super Mario World é um dos jogos de plataforma mais icônicos da Nintendo, onde Mario e Luigi embarcam em uma missão para resgatar a Princesa Toadstool e derrotar Bowser. Com uma jogabilidade envolvente, mundos expansivos e a introdução de Yoshi, o jogo é um marco na história dos videogames e uma parte essencial da franquia Mario.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Hollow Knight', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/7.png', 'Uma jornada sombria e desafiadora em um mundo subterrâneo.', 'Hollow Knight é um jogo de plataforma metroidvania onde os jogadores exploram o vasto e sombrio reino de Hallownest. Com uma jogabilidade fluida, um mundo interconectado, e uma história cheia de mistérios, o jogo oferece desafios intensos e recompensadores, tudo em um estilo artístico único e impressionante.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ori and the Blind Forest', 4, 2015, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/8.png', 'Uma aventura emocional e desafiadora com belíssimos gráficos.', 'Ori and the Blind Forest é um jogo de plataforma 2D que conta a história de Ori, uma criatura que deve restaurar a floresta perdida enquanto enfrenta uma jornada emocionante e cheia de desafios. O jogo é notável por sua arte deslumbrante, música emocionante e mecânicas de plataforma inovadoras.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Cuphead', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/9.png', 'Desafios de plataforma com estilo visual inspirado nos desenhos animados clássicos.', 'Cuphead é um jogo de plataforma e ação onde os jogadores controlam Cuphead ou Mugman, dois irmãos que enfrentam uma série de inimigos em batalhas frenéticas. O jogo é famoso por seu estilo artístico único, inspirado em desenhos animados dos anos 1930, e por seu nível de dificuldade implacável, oferecendo uma experiência desafiadora e visualmente deslumbrante.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sonic CD', 4, 1993, 'Platform', 'Sega CD, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/10.png', 'Uma clássica aventura do Sonic com viagem no tempo e ação eletrizante.', 'Sonic CD é um jogo de plataforma que apresenta Sonic enfrentando o vilão Dr. Robotnik (Eggman) em uma jornada através do tempo para salvar o futuro. Com gráficos vibrantes e inovadoras mecânicas de viagem no tempo, o jogo oferece uma experiência de velocidade e ação que se tornou um marco na franquia Sonic.');


INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 3, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 4, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 5, 4);

INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 6, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 7, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 8, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 9, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 10, 4);